CREATE USER 'user1'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database1;
GRANT ALL ON Database1 . * TO 'user1'@'localhost';
CREATE USER 'user2'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database2;
GRANT ALL ON Database2 . * TO 'user2'@'localhost';
CREATE USER 'user3'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database3;
GRANT ALL ON Database3 . * TO 'user3'@'localhost';
CREATE USER 'user4'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database4;
GRANT ALL ON Database4 . * TO 'user4'@'localhost';
CREATE USER 'user5'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database5;
GRANT ALL ON Database5 . * TO 'user5'@'localhost';
CREATE USER 'user6'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database6;
GRANT ALL ON Database6 . * TO 'user6'@'localhost';
CREATE USER 'user7'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database7;
GRANT ALL ON Database7 . * TO 'user7'@'localhost';
CREATE USER 'user8'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database8;
GRANT ALL ON Database8 . * TO 'user8'@'localhost';
CREATE USER 'user9'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database9;
GRANT ALL ON Database9 . * TO 'user9'@'localhost';
CREATE USER 'user10'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database10;
GRANT ALL ON Database10 . * TO 'user10'@'localhost';
CREATE USER 'user11'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database11;
GRANT ALL ON Database11 . * TO 'user11'@'localhost';
CREATE USER 'user12'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database12;
GRANT ALL ON Database12 . * TO 'user12'@'localhost';
CREATE USER 'user13'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database13;
GRANT ALL ON Database13 . * TO 'user13'@'localhost';
CREATE USER 'user14'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database14;
GRANT ALL ON Database14 . * TO 'user14'@'localhost';
CREATE USER 'user15'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database15;
GRANT ALL ON Database15 . * TO 'user15'@'localhost';
CREATE USER 'user16'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database16;
GRANT ALL ON Database16 . * TO 'user16'@'localhost';
CREATE USER 'user17'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database17;
GRANT ALL ON Database17 . * TO 'user17'@'localhost';
CREATE USER 'user18'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database18;
GRANT ALL ON Database18 . * TO 'user18'@'localhost';
CREATE USER 'user19'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database19;
GRANT ALL ON Database19 . * TO 'user19'@'localhost';
CREATE USER 'user20'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database20;
GRANT ALL ON Database20 . * TO 'user20'@'localhost';
CREATE USER 'user21'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database21;
GRANT ALL ON Database21 . * TO 'user21'@'localhost';
CREATE USER 'user22'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database22;
GRANT ALL ON Database22 . * TO 'user22'@'localhost';
CREATE USER 'user23'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database23;
GRANT ALL ON Database23 . * TO 'user23'@'localhost';
CREATE USER 'user24'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database24;
GRANT ALL ON Database24 . * TO 'user24'@'localhost';
CREATE USER 'user25'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database25;
GRANT ALL ON Database25 . * TO 'user25'@'localhost';
CREATE USER 'user26'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database26;
GRANT ALL ON Database26 . * TO 'user26'@'localhost';
CREATE USER 'user27'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database27;
GRANT ALL ON Database27 . * TO 'user27'@'localhost';
CREATE USER 'user28'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database28;
GRANT ALL ON Database28 . * TO 'user28'@'localhost';
CREATE USER 'user29'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database29;
GRANT ALL ON Database29 . * TO 'user29'@'localhost';
CREATE USER 'user30'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database30;
GRANT ALL ON Database30 . * TO 'user30'@'localhost';
CREATE USER 'user31'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database31;
GRANT ALL ON Database31 . * TO 'user31'@'localhost';
CREATE USER 'user32'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database32;
GRANT ALL ON Database32 . * TO 'user32'@'localhost';
CREATE USER 'user33'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database33;
GRANT ALL ON Database33 . * TO 'user33'@'localhost';
CREATE USER 'user34'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database34;
GRANT ALL ON Database34 . * TO 'user34'@'localhost';
CREATE USER 'user35'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database35;
GRANT ALL ON Database35 . * TO 'user35'@'localhost';
CREATE USER 'user36'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database36;
GRANT ALL ON Database36 . * TO 'user36'@'localhost';
CREATE USER 'user37'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database37;
GRANT ALL ON Database37 . * TO 'user37'@'localhost';
CREATE USER 'user38'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database38;
GRANT ALL ON Database38 . * TO 'user38'@'localhost';
CREATE USER 'user39'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database39;
GRANT ALL ON Database39 . * TO 'user39'@'localhost';
CREATE USER 'user40'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database40;
GRANT ALL ON Database40 . * TO 'user40'@'localhost';
CREATE USER 'user41'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database41;
GRANT ALL ON Database41 . * TO 'user41'@'localhost';
CREATE USER 'user42'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database42;
GRANT ALL ON Database42 . * TO 'user42'@'localhost';
CREATE USER 'user43'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database43;
GRANT ALL ON Database43 . * TO 'user43'@'localhost';
CREATE USER 'user44'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database44;
GRANT ALL ON Database44 . * TO 'user44'@'localhost';
CREATE USER 'user45'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database45;
GRANT ALL ON Database45 . * TO 'user45'@'localhost';
CREATE USER 'user46'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database46;
GRANT ALL ON Database46 . * TO 'user46'@'localhost';
CREATE USER 'user47'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database47;
GRANT ALL ON Database47 . * TO 'user47'@'localhost';
CREATE USER 'user48'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database48;
GRANT ALL ON Database48 . * TO 'user48'@'localhost';
CREATE USER 'user49'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database49;
GRANT ALL ON Database49 . * TO 'user49'@'localhost';
CREATE USER 'user50'@'localhost' IDENTIFIED BY 'P@ssw0rd';
CREATE DATABASE Database50;
GRANT ALL ON Database50 . * TO 'user50'@'localhost';
